// angular/movies-searcher/src/app/components/Movie/movie.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'movie',
  templateUrl: './movie.component.html',
  styleUrls: ['./movie.component.css']
})
export class MovieComponent {

  @Input() movie: any

  constructor() { }

}

<div class="movie" *ngIf='movie.Poster != "N/A"'>
    <a routerLink="/details/{{movie.imdbID}}" class="card">
        <figure>
            <img src={{movie.Poster}} alt={{movie.Title}}>
        </figure>
        <div>
            <p>{{movie.Title}}</p>
            <p>{{movie.Year}}</p>
        </div>
    </a>
</div>

// react/src/components/Movie/Movie.js
import PropTypes from 'prop-types'
import { Link } from 'react-router-dom'
import './Movie.css'

const Movie = ({ id, title, year, poster }) => (
	<Link to={`/detail/${id}`} className='card'>
		<div className='card-img'>
			<figure>
				<img src={poster} alt={title} />
			</figure>
		</div>
		<div className='card-content'>
			<div className=''>
				<div className=''>
					<p className='title'>{title}</p>
					<p className='subtitle'>{year}</p>
				</div>
			</div>
		</div>
	</Link>
)

export default Movie

Movie.propTypes = {
	id: PropTypes.string,
	title: PropTypes.string,
	year: PropTypes.string,
	poster: PropTypes.string,
}
