// vue/movies-searcher/src/components/Movie.vue
<template>
    <div class="detail">
        <img :src='movie.Poster'>
        <p>{{ movie.Title }}</p>
        <p>{{ movie.Year }}</p>
    </div>
</template>

<script>
    export default {
        name: 'Movie',
        props: ['movie']
    }
</script>

<style scoped>
    .detail:hover{
        cursor: pointer;
    }
</style>

// react/src/components/Movie/Movie.js
import PropTypes from 'prop-types'
import { Link } from 'react-router-dom'
import './Movie.css'

const Movie = ({ id, title, year, poster }) => (
	<Link to={`/detail/${id}`} className='card'>
		<div className='card-img'>
			<figure>
				<img src={poster} alt={title} />
			</figure>
		</div>
		<div className='card-content'>
			<div className=''>
				<div className=''>
					<p className='title'>{title}</p>
					<p className='subtitle'>{year}</p>
				</div>
			</div>
		</div>
	</Link>
)

export default Movie

Movie.propTypes = {
	id: PropTypes.string,
	title: PropTypes.string,
	year: PropTypes.string,
	poster: PropTypes.string,
}
