// react/src/components/SearchForm/SearchForm.js
import { useState } from 'react'
import { useHistory } from 'react-router-dom'
import './SearchForm.css'

const SearchForm = () => {
	const [query, setQuery] = useState('')
	const history = useHistory()

	const handleSubmit = async (e) => {
		e.preventDefault()
		if (query.trim() === '') return
		history.push(`/results/1/${query}`)
	}

	return (
		<form onSubmit={handleSubmit}>
			<input
				className='searchform-input'
				onChange={(e) => setQuery(e.target.value)}
				placeholder='Find a movie...'
				type='text'
				autoFocus
			/>
			<button className='button'>Search</button>
		</form>
	)
}

export default SearchForm

// angular/src/app/components/SearchForm/search-form.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormControl } from '@angular/forms';
import { debounceTime } from 'rxjs/operators';
import { Router } from '@angular/router';

@Component({
  selector: 'searchform',
  templateUrl: './search-form.component.html',
  styleUrls: ['./search-form.component.css'],
})
export class SearchFormComponent implements OnInit {
  constructor(private router: Router) {}

  ngOnInit(): void {
    this.search.valueChanges
      .pipe(debounceTime(300))
      .subscribe((value) => this.searchEmitter.emit(value as any));
  }

  searchMovie(e: Event) {
    e.preventDefault();
    if (this.search.value && this.search.value.trim() !== '') {
      this.router.navigate(['/results/1/', this.search.value]);
    }
  }

  search = new FormControl('');

  @Output('search') searchEmitter = new EventEmitter<string>();
}

<form>
    <input class="input" [formControl]='search' placeholder="Find a movie..." spellcheck="false" />
    <button class="button" (click)='searchMovie($event)'>Search</button>
</form>
