// react-native/app/screens/Details.js
import React from 'react'
import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Card } from 'react-native-elements'
import { Background, Info } from '../components'
import useMovie from '../hooks/useMovie'

const Details = ({ route }) => {
	const {
		Actors,
		Awards,
		Country,
		Director,
		Genre,
		Metascore,
		Plot,
		Poster,
		Production,
		Ratings,
		Released,
		Runtime,
		Title,
		Type,
		Writer,
	} = useMovie({ route })

	return (
		<SafeAreaView style={{ flex: 1 }}>
			<ScrollView>
				<Background>
					<Card containerStyle={styles.card}>
						<Card.Title>{Title}</Card.Title>
						<Card.Image
							source={{ uri: Poster }}
							style={styles.image}></Card.Image>
						<View style={styles.details}>
							<Info text={Actors} title='Actors' />
							<Info text={Plot} title='Description' />
							{Awards && <Info text={Awards} title='Awards' />}
							{Country && <Info text={Country} title='Country' />}
							{Metascore && (
								<Info text={Metascore} title='Metascore' />
							)}
							{Director && (
								<Info text={Director} title='Director' />
							)}
							{Genre && <Info text={Genre} title='Genre' />}
							{Production && (
								<Info text={Production} title='Production' />
							)}
							{Ratings && (
								<View>
									<Text>Ratings:</Text>
									{Ratings.map((rating, index) => (
										<Text key={index}>
											Source: {rating.Source} - Value:{' '}
											{rating.Value}
										</Text>
									))}
								</View>
							)}
							{Released && (
								<Info text={Released} title='Released' />
							)}
							{Runtime && <Info text={Runtime} title='Runtime' />}
							{Type && <Info text={Type} title='Type' />}
							{Writer && <Info text={Writer} title='Writer' />}
						</View>
					</Card>
				</Background>
			</ScrollView>
		</SafeAreaView>
	)
}

const styles = StyleSheet.create({
	card: {
		backgroundColor: '#ffffffa3',
		marginBottom: 15,
	},
	image: {
		width: '100%',
		height: 500,
		resizeMode: 'contain',
	},
	details: {
		marginTop: 15,
	},
})

export default Details

// vue/src/views/Details.vue
<template>
  <div class="container">
    <button class="button" @click="goBack">Go Back</button>
    <h1>{{ details.title }}</h1>
    <div>
      <img :src="details.poster" :alt="details.title" />
    </div>
    <h3>Actors: {{ details.actors }}</h3>
    <p>Description: {{ details.plot }}.</p>
    <div>
      <p>Awards: {{ details.awards }}.</p>
      <p>Country: {{ details.country }}.</p>
      <p>Metascore: {{ details.metascore }}.</p>
      <p>Director: {{ details.director }}.</p>
      <p>Genre: {{ details.genre }}.</p>
      <p>Production: {{ details.production }}.</p>
      <p>Ratings:</p>
      <p v-for="rating of details.ratings" :key="rating.imdbID">Source: {{ rating.Source }} - Value: {{ rating.Value }}</p>

      <p>Released: {{ details.released }}.</p>
      <p>Runtime: {{ details.runtime }}.</p>
      <p>Type: {{ details.type }}.</p>
      <p>Writer: {{ details.writer }}.</p>
    </div>
  </div>
</template>

<script>
import { mapActions } from 'vuex'

export default {
  name: 'details-view',
  mounted() {
    this.getDetails()
  },
  methods: {
    ...mapActions(['fetchDetails']),
    getDetails: function () {
      return this.$store.dispatch('fetchDetails', { id: this.$route.params.id })
    },
    goBack() {
      this.$router.go(-1)
    }
  },
  computed: {
    details() {
      return {
        actors: this.$store.state.actors,
        awards: this.$store.state.awards,
        country: this.$store.state.country,
        director: this.$store.state.director,
        genre: this.$store.state.genre,
        metascore: this.$store.state.metascore,
        plot: this.$store.state.plot,
        poster: this.$store.state.poster,
        production: this.$store.state.production,
        ratings: this.$store.state.ratings,
        released: this.$store.state.released,
        runtime: this.$store.state.runtime,
        title: this.$store.state.title,
        type: this.$store.state.type,
        writer: this.$store.state.writer
      }
    }
  }
}
</script>

<style scoped>
.container {
  text-align: center;
}
.button {
  width: 100%;
  height: 2.38rem;
  background-color: rgba(29, 219, 70, 0.7411764705882353);
}
.button:hover {
  background-color: #1ddb46;
  cursor: pointer;
}
</style>
